import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Linnéa's Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.centerBox}>
          <h2>Get your popcorn ready... 🍿</h2>
            <a className={styles.linkButton} href="/movies/popular">Browse movies</a>
            <a  className={styles.linkButton} href="/register">Register</a>
        </div>
      </>
  )
}